import { Button, GridBox, VerticalBox, LineEdit} from "std-widgets.slint";
export global Button-comp-click{
    callback button-pressed(string);
}
export component Button-comp inherits Button {
    height: 50px;
    width: 100px;
    clicked => {Button-comp-click.button-pressed(root.text); } 
}

export component Calc inherits Window {
    callback result-clicked(string);
    callback word-typed(string);
    in property <string> result: "";
    in-out property <string> inputo: "";
    default-font-size: 22px;
    width: 440px;
    height: 600px;
    title: "Calculadorazuda";

    my-key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.Backspace) {
                word-typed("delete");
            }else{
                word-typed(event.text);
            }
            accept
        }
    
        // Grid main
    GridBox {
        preferred-width: 100%;
        preferred-height: 100%;
        spacing: 0;

        // Grid do historico e input
        GridBox {
            col: 0;
            row: 0;
            spacing: 0;
            spacing-horizontal: 0;
            height: 50%;

            // tela do historico
        Rectangle {
                height: 70%;
                background: cadetblue;
                row: 0;
                Text {
                    color: black;
                    font-weight: 500;
                    text: root.result;
                }
            }

            // tela de escrita
                input := Text {
                vertical-alignment: center;
                text: inputo;
                row: 1;
            }
        }
        // Grid dos botoes
    GridBox {
            row: 1;
            col: 0;
            preferred-width: 100%;
            height: 50%;
            spacing: 0;
            spacing-horizontal: 0;
            // botoes de cima
        GridLayout {
                col: 0;
                spacing: 5px;
                padding-bottom: 5px;
                padding-right: 5px;
                Button-comp {
                    text: "AC";
                    clicked => {root.inputo = ""}
                }

                Button-comp {
                    text: "+/-";
                }

                Button-comp {
                    text: "%";
                }
            }

            // Numeros
            GridLayout {
                spacing: 5px;
                row: 1;
                Row {
                    Button-comp {
                        text: "7";
                    }

                    Button-comp {
                        text: "8";
                    }

                    Button-comp {
                        text: "9";
                    }
                }

                Row {
                    Button-comp {
                        text: "4";
                    }

                    Button-comp {
                        text: "5";
                    }

                    Button-comp {
                        text: "6";
                    }
                }

                Row {
                    Button-comp {
                        text: "1";
                    }

                    Button-comp {
                        text: "2";
                    }

                    Button-comp {
                        text: "3";
                    }
                }

                Row {
                    Button {
                        colspan: 2;
                        text: "0";
                    }

                    Button-comp {
                        text: ",";
                        col: 2;
                    }
                }
            }

            // operacoes
            GridLayout {
                spacing: 5px;
                row: 0;
                rowspan: 2;
                col: 1;
                Row {
                    Button-comp {
                        text: "/";
                    }
                }

                Row {
                    Button-comp {
                        text: "x";
                    }
                }

                Row {
                    Button-comp {
                        text: "-";
                    }
                }

                Row {
                    Button-comp {
                        text: "+";
                    }
                }

                Row {
                    Button-comp {
                        text: "=";
                        clicked => {
                            result-clicked(input.text);
                        }
                    }
                }
            }
        }
    }
}
}
